### ISSUE TITLE
cssModule 问题

### ISSUE THREAD

**Issue by ikimiler** [swcbo/react-ts-h5-template#3]
你好，我在使用cssModule的时候遇到了错误

Error: Can't find stylesheet to import.
    ╷
  1 │ @import "./src/assets/css/variables.scss";$cardWidth: 46vw;
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    src\pages\home\home.module.scss 1:9  root stylesheet

需要怎么解决呀，另外方便留一个联系方式吗。。

**Comment by swcbo** [comment]
可以加我wx17512036504




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月5日(星期三) 下午4:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [swcbo/react-ts-h5-template] cssModule 问题 (Issue #3)





 
你好，我在使用cssModule的时候遇到了错误
 
Error: Can't find stylesheet to import.
 ╷
 1 │ @import "./src/assets/css/variables.scss";$cardWidth: 46vw;
 │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 ╵
 src\pages\home\home.module.scss 1:9  root stylesheet
 
需要怎么解决呀，另外方便留一个联系方式吗。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
