### ISSUE TITLE
打包后postcss-pxtorem没有转换，还是px

### ISSUE THREAD

**Issue by a869057476** [swcbo/react-ts-h5-template#4]

**Comment by swcbo** [comment]
问下是说的三方依赖库的没有转换 还是项目本身

**Comment by a869057476** [comment]
> 问下是说的三方依赖库的没有转换 还是项目本身
项目本身，该项目是拿你这个项目clone下来做的，但是不知道为何打包后间歇性px转换失效
https://github.com/a869057476/activity-h5

**Comment by a869057476** [comment]
大佬，您可以看看我项目的提交记录帮我分析一下吗
https://github.com/a869057476/activity-h5

**Comment by swcbo** [comment]
可以的 稍等哈

**Comment by swcbo** [comment]
我看了下没问题 可以加我微信 17512036504 发下对应截图

**Comment by swcbo** [comment]
降级 postcss-pxtorem  => 5.1.1
