### ISSUE TITLE
history 依赖找不到

### ISSUE THREAD

**Issue by hu5871** [swcbo/react-ts-h5-template#5]
package是否完整

**Comment by swcbo** [comment]
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/15608472/192913296-6bd87f17-d8e0-4d96-b0c9-8c526aeb99d5.png">

react-router-dom 旧版本内部依赖history，高版本已经移除可以自行安装 history
🔨后续会上传yarn.lock 文件

**Comment by swcbo** [comment]
已上传yarn.lock  项目添加history依赖
